# Generated by Django 5.2.6 on 2025-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleAway', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, help_text='S3 bucket URL for the listing image', max_length=500, null=True),
        ),
    ]
